import { currency } from "./data";
import { icon, escape as esc } from "./icons";
import { adventureNavigation, worldMark } from "./navigation";

export function hudMarkup() {
  return `    <div id="hud" class="hud hidden"><div class="hud-top"><div class="location-pill">${worldMark()}<span id="location-name">Hearthwick<small>SAFE HAVEN</small></span></div><div class="hud-top-right"><button id="presence" class="presence" data-action="panel:explorers" title="View explorers and invite a friend">1 explorer online</button><button id="room-code" data-action="copy-room" class="text-button" title="Copy island code for a friend"></button><button id="account-pill" class="account-pill" data-action="panel:wop" title="Wallet and $WOP"></button><button class="balance-pill" data-action="panel:ledger">${icon("coin")}<span id="balance">0</span><small>${esc(currency)}</small></button><button data-action="panel:appearance" class="icon-button dark" aria-label="Character studio">${icon("team")}</button><button data-action="panel:settings" class="icon-button dark" aria-label="Settings">${icon("settings")}</button></div></div>
      <div class="quest-tracker" id="quest-tracker"></div><button class="minimap" data-action="panel:map" aria-label="Open island map"><canvas id="minimap" width="180" height="180"></canvas><span>ASTER ISLE <kbd>M</kbd></span></button><div id="target-card" class="target-card hidden"></div>
      <div class="hud-bottom"><div class="party-dock" aria-label="Trainer and Pokémon"><div id="companion-card" class="unit-frames"></div><div id="pet-abilities" class="pet-abilities"></div></div><div class="combat-center"><div id="duel-banner" class="duel-banner hidden"></div><div id="interaction" class="interaction"></div><div id="combat-status" class="combat-status">Choose a creature · Tab to target nearest</div><div id="cast-bar" class="cast-bar hidden" role="status"><span class="cast-fill"></span><span class="cast-name"></span><span class="cast-time"></span></div><div id="abilities" class="ability-bar"></div><div id="xp-bar" class="xp-bar"><span class="xp-fill"></span><span class="xp-text"></span></div><div class="combat-hint"><kbd>1–6</kbd> Abilities <span>·</span> <kbd>T</kbd> Auto attack <span>·</span> <kbd>Tab</kbd> Target</div></div>${adventureNavigation()}</div>
      <div id="combat-log" class="combat-log" aria-live="off"></div><div id="chat" class="chat"></div><div id="error-line" class="error-line" role="status"></div><div id="level-banner" class="level-banner hidden"></div><div id="defeat-banner" class="defeat-banner hidden"><strong>Defeated</strong><span>Your spirit returned to Hearthwick. Visit the Springhouse to be healed for free.</span></div>
      <div class="movement-hint"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> MOVE <span>SHIFT</span> SPRINT <span>E</span> INTERACT</div>
    </div>
`;
}
